exports.listAllRolePermission = [
    {
        id: 1,
        label: 'List and Detail',
        name: 'List',
        modules: 'Bank',
        menu: 'Bank',
    },
    {
        id: 2,
        label: 'Add',
        name: 'Add',
        modules: 'Bank',
        menu: 'Bank',
    },
    {
        id: 3,
        label: 'Edit',
        name: 'Edit',
        modules: 'Bank',
        menu: 'Bank',
    },
    {
        id: 4,
        label: 'Approval',
        name: 'Approval',
        modules: 'Bank',
        menu: 'Bank',
    },
    {
        id: 5,
        label: 'List and Detail',
        name: 'List',
        modules: 'Borrower',
        menu: 'Nasabah',
    },
    {
        id: 6,
        label: 'Add',
        name: 'Add',
        modules: 'Borrower',
        menu: 'Nasabah',
    },
    {
        id: 7,
        label: 'Edit',
        name: 'Edit',
        modules: 'Borrower',
        menu: 'Nasabah',
    },
    {
        id: 8,
        label: 'Approval',
        name: 'Approval',
        modules: 'Borrower',
        menu: 'Nasabah',
    },
    {
        id: 9,
        label: 'List and Detail',
        name: 'List',
        modules: 'Loan',
        menu: 'Pinjaman',
    },
    {
        id: 10,
        label: 'Add',
        name: 'Add',
        modules: 'Loan',
        menu: 'Pinjaman',
    },
    {
        id: 11,
        label: 'Edit',
        name: 'Edit',
        modules: 'Loan',
        menu: 'Pinjaman',
    },
    {
        id: 12,
        label: 'Approval',
        name: 'Approval',
        modules: 'Loan',
        menu: 'Pinjaman',
    },
    {
        id: 13,
        label: 'List and Detail',
        name: 'List',
        modules: 'BankService',
        menu: 'Layanan',
    },
    {
        id: 14,
        label: 'Add',
        name: 'Add',
        modules: 'BankService',
        menu: 'Layanan',
    },
    {
        id: 15,
        label: 'Edit',
        name: 'Edit',
        modules: 'BankService',
        menu: 'Layanan',
    },
    {
        id: 16,
        label: 'Approval',
        name: 'Approval',
        modules: 'BankService',
        menu: 'Layanan',
    },
    {
        id: 17,
        label: 'List and Detail',
        name: 'List',
        modules: 'ServiceProduct',
        menu: 'Produk',
    },
    {
        id: 18,
        label: 'Add',
        name: 'Add',
        modules: 'ServiceProduct',
        menu: 'Produk',
    },
    {
        id: 19,
        label: 'Edit',
        name: 'Edit',
        modules: 'ServiceProduct',
        menu: 'Produk',
    },
    {
        id: 20,
        label: 'Approval',
        name: 'Approval',
        modules: 'ServiceProduct',
        menu: 'Produk',
    },
    {
        id: 21,
        label: 'List and Detail',
        name: 'List',    
        modules: 'BankType',
        menu: 'Tipe Bank',
    },
    {
        id: 22,
        label: 'Add',
        name: 'Add',
        modules: 'BankType',
        menu: 'Tipe Bank',
    },
    {
        id: 23,
        label: 'Edit',
        name: 'Edit',
        modules: 'BankType',
        menu: 'Tipe Bank',
    },
    {
        id: 24,
        label: 'Approval',
        name: 'Approval',
        modules: 'BankType',
        menu: 'Tipe Bank',
    },
    {
        id: 25,
        label: 'List and Detail',
        name: 'List',
        modules: 'loanPurposes',
        menu: 'Tujuan',
    },
    {
        id: 26,
        label: 'Add',
        name: 'Add',
        modules: 'loanPurposes',
        menu: 'Tujuan',
    },
    {
        id: 27,
        label: 'Edit',
        name: 'Edit',
        modules: 'loanPurposes',
        menu: 'Tujuan',
    },
    {
        id: 28,
        label: 'Approval',
        name: 'Approval',
        modules: 'loanPurposes',
        menu: 'Tujuan',
    },
    {
        id: 29,
        label: 'List and Detail',
        name: 'List',
        modules: 'Role',
        menu: 'Role',
    },
    {
        id: 30,
        label: 'Add',
        name: 'Add',
        modules: 'Role',
        menu: 'Role',
    },
    {
        id: 31,
        label: 'Edit',
        name: 'Edit',
        modules: 'Role',
        menu: 'Role',
    },
    {
        id: 32,
        label: 'Approval',
        name: 'Approval',
        modules: 'Role',
        menu: 'Role',
    },
    {
        id: 33,
        label: 'List and Detail',
        name: 'List',
        modules: 'Permission',
        menu: 'Role Permission',
    },
    {
        id: 34,
        label: 'Add',
        name: 'Add',
        modules: 'Permission',
        menu: 'Role Permission',
    },
    {
        id: 35,
        label: 'Edit',
        name: 'Edit',
        modules: 'Permission',
        menu: 'Role Permission',
    },
    {
        id: 36,
        label: 'Approval',
        name: 'Approval',
        modules: 'Permission',
        menu: 'Role Permission',
    },
  ]